<a href="https://colab.research.google.com/github/ayush2281/Pytorch-for-ML-DL-/blob/main/chapter_00__Pytorch__fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamental


In [ ]:
print("Hey Im excited to start pytorch")

Hey Im excited to start pytorch


The torch library is the core component of PyTorch, and it provides the fundamental building blocks for creating and working with neural networks

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


 Introduction of tensor

Creating Tensor

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

0--> dimensions

In [ ]:
# get a tensor back as python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
Tensor = torch.tensor([[[1,2,3],
                      [9,5,2],
                      [5,7,6]]])
Tensor

tensor([[[1, 2, 3],
         [9, 5, 2],
         [5, 7, 6]]])

In [ ]:
# dimensions
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

### Random Tensors

Why random tensor?

random tensor are very important because the way many network learn is that they start with tensor full of random numbers and then adjust those random numbver sto better represent the data.

In [ ]:
# Random Tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1268, 0.8988, 0.4644, 0.5064],
        [0.4357, 0.1493, 0.6990, 0.1938],
        [0.0610, 0.9428, 0.3676, 0.1392]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor  = torch.rand(size=(3,224,224))  # height , width , cooour channel (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
## zeros and ones
# create a tensor of all zeors
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create an tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
ones.shape

torch.Size([3, 4])

In [ ]:
ones.ndim

2

Creating a range of tensor and tensor like

In [ ]:
# use torch.range()
# torch.range(0,10)
one_to_ten = torch.arange(start=0,end=100, step=10)
one_to_ten

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# creating the tensor like

In [ ]:
#creating the tensor like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor datatypes**

**NOTE:** : tensor datatype is one of the
3 big error you will run with pytorch & deeep learning.
1. Tensor not right datatype
2. Tensor not right shape
3. tensor not on the right device

In [ ]:
# float 32  tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2720, 0.0094, 0.3605, 0.9613],
        [0.3142, 0.5819, 0.8168, 0.3588],
        [0.7504, 0.0693, 0.3429, 0.3653]])

In [ ]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.2720, 0.0094, 0.3605, 0.9613],
        [0.3142, 0.5819, 0.8168, 0.3588],
        [0.7504, 0.0693, 0.3429, 0.3653]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
# both give the same output but one is function and another is attributes
some_tensor.size() , some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

### Manipulating Tensors (Tensors OPeration)
  Tensors Operations
1. Addition
2. Substraction
3. Mutiplicatio
4. Devision
5. Matrix Multipication


In [ ]:
# cfreate an tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply by 10
tensor = torch.tensor([5,5,5])
tensor * 10

tensor([50, 50, 50])

In [ ]:
tensor

tensor([5, 5, 5])

In [ ]:
#  subtract
tensor = torch.tensor([9,3,4])
tensor -5

tensor([ 4, -2, -1])

In [ ]:
# try out in pytorch build function
torch.mul(tensor,10)

tensor([90, 30, 40])

In [ ]:
# original value of tensor
tensor


tensor([9, 3, 4])

In [ ]:
# divison
tensor = torch.tensor([1,2,3])
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

# there is two ways to matrix multiplication in deep learn and nerual netwrk
1. element-wise
2. Matrix multiplication (dot product)

there are two main rules that performing matrix multiplication needs to satisfy:


1. The **inner dimension** must match:


*   (3, 2) @ (3,2) wont work
*   (3, 2) @ (2,3) will work
*   (2,3)  @ (3,2) will work

2. the **outer dimension**
the resulting matrix has the shape of the **outer dimension**

* (2,3) (3,2) -> (2,2)
* (3,2) (2,3) -> (3,2)





In [ ]:
# element wise
# matrix multiplication
tensor_1 = torch.tensor([1,5,6]) * torch.tensor([2,3,4])
tensor_1

tensor([ 2, 15, 24])

In [ ]:
# matrix multilication
%%time
torch.matmul(tensor_1, tensor_1)

CPU times: user 0 ns, sys: 637 µs, total: 637 µs
Wall time: 7.59 ms


tensor(805)

In [ ]:
# see it is faild because inner dimension is not matched
tensr = torch.matmul(torch.rand(3,2), torch.rand(3,2))
tensr

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# see it is faild because inner dimension is not matched
tensr = torch.matmul(torch.rand(3,2), torch.rand(2,3))
tensr

In [ ]:
# matrix multiplication by hand
2*2 + 15*15 + 24*24

In [ ]:
%%time
value = 0
for i in range(len(tensor_1)):
  value += tensor_1[i] * tensor_1[i]
print(value)


**One of the most commin erros in deep : shape error**

In [ ]:
# Shape for the matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.matmul(tensor_A, tensor_B)


In [ ]:
tensor_A.shape, tensor_B.shape

chanege the shape of any mat

In [ ]:
# we can use the transpose
tensor_B.T, tensor_B.T.shape, "Original shape",tensor_B.shape


In [ ]:
# th matrix multiplication opearation works with tensor_B is transposed
torch.matmul(tensor_A, tensor_B.T)


## finding the min , amx , sum , etc (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(1, 100, 10)
x

In [ ]:
# find the min
torch.min(x), x.min()

In [ ]:
# find the max
torch.max(x), x.max()

In [ ]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
# find the sum
torch.sum(x), x.sum()

## Find the positional min and max

In [ ]:
x


In [ ]:
# find the position in tensor that has the minimun value with argmin()-> returns in
x.argmin()

In [ ]:
x[0]

In [ ]:
x.argmax()

find the positional min and  max

In [ ]:
x[9]

In [ ]:
x

## reshaping the stacking , squeeezing and unsqueezing tensors

* Reshaping - reshapes an input te tensor to defined shape

* View - Return a view of an input tensor of certain chape but keep the same memory as the original  tensor

* Stacking : combine multiple tensor on top of each other (vstack) or side by side

* Unsequeeze : addd a 1 dimension to a target tensor

* Permute : Return a view of the input with dimension permute (swapped) in a certain way.

In [ ]:
#Lets create an tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

In [ ]:
   # change the view
z = x.view(1, 9)
z, z.shape


In [ ]:
# changing z changes x because a view a tensor share the same meomory a sthe original
z[:, 0] = 5
z, x

In [ ]:
# stack tye tensor in the top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

In [ ]:
#  torch.sequeeze() - remove all single dimension from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")



In [ ]:
# torch unsqueeze() - adds dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

In [ ]:
x_reshaped.squeeze()

In [ ]:
x_reshaped.squeeze().shape

In [ ]:
# torch.permute - rearrange the dimension of  a target in a specified order
x = torch.randn(2,3,5)
x.size()
torch.permute(x, (2,0,1)).size() # 2,0,1 is showing the index number of the 2,3,5 it will arrange in this manner

## indexing (Selecting data from tensors)

indeximg with Pytorch is similar to insexing with Numpy.

In [ ]:
## creating a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

In [ ]:
# let's index on new tensor
x[0]

In [ ]:
#lets index on the middle bracket dim=1
x[0] [0]

In [ ]:
# lets index the most inner bracket
x[0] [0] [0]

In [ ]:
# lets the inner on the most brackets (last dimenesion)
x[0][1][1]

In [ ]:
x[0][2][2]

In [ ]:
# get all the value of the 0 dimension but only the 1 index value of 1st and 2nd diemsion

x[: , 1 , 1]

In [ ]:
# get the index 0 of 0th and 1sy dimesion and all values of 2nd dimesnion
x[0,0,:]

In [ ]:
# ondex on  the x to return 9
print(x[0] [2] [2])

# indexing on x to returns 3,6,9
print(x[0,:,2])


NameError: name 'x' is not defined

## Pytorch tensors & Numpy

Numpy is a popular scientific python numerical computing library.

And because of this , Pytorch has functionallity to intteract with it
* data in Numpy, want in pytorch -> torch.from_numpy(ndarray)
* Pytorcch tensor -> Numpy-> torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import numpy as np
import torch

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)   # warning when converting from numpy--> pytorch reflects numpy default datatype of the float64 unless specified otheriwse
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# change th evalue of error , what will this do to 'tensor'?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
tensor.dtype

torch.float32

In [ ]:
# change the tensor -> what happens to the numpy
tensor = tensor + 1
tensor, numpy_tensor

In [ ]:
numpy_tensor.dtype

## Reproducibility (ttruing to take random out of random)

in short how a neural network learns:

start with random numbers -> tensor operation -> update random numbers to try and make them better representaion of the data -> again-> again-> again.

To reduce the randomness in neural network and pytorch comes with concept of a **random seed**.

Essentially what the random seed does is 'floavour' the randomness.

In [ ]:
# import torch
# create twon random tesors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5615, 0.1303, 0.1790, 0.1256],
        [0.5668, 0.6054, 0.9698, 0.9131],
        [0.9518, 0.5540, 0.8135, 0.2471]])
tensor([[0.1790, 0.9394, 0.9536, 0.3423],
        [0.3636, 0.1774, 0.1052, 0.1002],
        [0.9070, 0.8514, 0.1779, 0.4880]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets make some random reproducicle tessors
import torch

# set the random seed
Random_seed = 42
torch.manual_seed(Random_seed)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(Random_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
https://pytorch.org/docs/stable/notes/randomness.html

Running tensors and pytorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA Hardware +Pytorch working behind the scenes to make everything hunky dory (good).

In [ ]:
# ## Getting a GPU
# Eassist way to use --> google colab-> what we are usig .
# use yourt own gpu but requires the investment because its expensive

# you use cloud gpu -GCP, AWS AZURE

2. Check the GPU access with Pytorch

In [ ]:
# cchecking for the GPU acees with pytorch
import torch
torch.cuda.is_available()

False

because I'm using free version of the google colab thats its false.

In [ ]:
#setup device agnostic code
devise = 'cuda' if torch.cuda.is_available() else 'cpu'
devise

'cpu'

CPU because we use free version of colab.

In [ ]:
# count numbe rof devices
torch.cuda.device_count()

0

For Pytorch since its capable of running compute on the GPU or CPu its best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda
E.g. run on the gpu if available else on CPU by default

3.  putting the tensor and models on the GPU
the reseas we want to our tensor/model on tye gPU is because using a GPU result in faster computrational.

In [ ]:
# create a tesor (default on the Cpu)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
#  Move Tensor to GPU (if available)
tensor_on_gpu = tensor.to(devise)
tensor_on_gpu

tensor([1, 2, 3])

it did'nt move on the gpu because we dont have paid plan we are uisng the free plan which is on cpu

### 4. moving tensor back to the CPU

In [ ]:
# if tensor is on gpu , can't tranforn it to numpy
tensor_on_gpu.numpy()


array([1, 2, 3])

it will be show error if we have paid plan or if we are on the gpu

In [ ]:
# TO FIX THE GPU TENSOR WITH NUMPY ISSUE , WE CAN FIRST SET IT TO THE CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

**Caution:** - it is for the GPU . we are using the free colab.

## Excercises & extra cariculum
See: https://www.learnpytorch.io/00_pytorch_fundamentals/#extra-curriculum